steps:

  # ! build
  # installation des dépendances 
  # un "builder" est un container avec certaines dépendances pré installées
  - name: python # nom du "builder"
    # nom du programme en entrée pour cette étape de pipeline
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
    id: "installation des dépendances"

    # ! test
  - name: python
    # nom du programme en entrée pour cette étape de pipeline
    entrypoint: python
    args: ["-m", "pytest"]
    id: "test de l'application"

    # ! deploy
  # build l'image Docker de l'application
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/airy-boulevard-412810/serfa-gcp/flasksample:$SHORT_SHA",
        "-f",
        "prod.dockerfile",
        ".",
      ]
    id: Build
  # push de l'image sur Google Artifact Registry 
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "/flasksample:$SHORT_SHA"
    id: Push
    
    # TODO déployer cette image en tant que service Cloud Run
      identifiant : Push

    # TODO déployer cette image en tant que service Cloud Run
  # déployé sur Google Cloud Run
  - nom : " gcr.io/google.com/cloudsdktool/cloud-sdk:slim "
    arguments :
      - courir
      - prestations de service
      - mise à jour
      - serfa-gcp-tp
      - " --platform=géré "
      - "europe-west1-docker.pkg.dev/airy-boulevard-412810/serfa-gcp/flasksample:$SHORT_SHA "
      - " --region=europe-west1 "
      - " --calme "
    identifiant : Déployer
    point d'entrée : gcloud
