steps:

  # ! build
  # installation des dépendances test commit isaac
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
    id: "Install"

    # ! test
    # TODO
    - name: python
      entrypoint: python
      args: ["-m", "pytest"]
      id: "Test"

    # ! deploy
    # TODO
